### ISSUE TITLE
FluentAvalonia v2 Roadmap

### ISSUE THREAD

**Issue by amwx** [amwx/FluentAvalonia#238]
I think at this point the biggest changes have been made for v2/Avalonia 11.0, both here an upstream - at least in terms of the public API. FA is now (or at least should be) compatible out-of-the-box on all backends, however, if you find something gives you trouble do raise an issue. I know very little about the wasm/mobile stuff and may not be able to help all that much, but someone else might - and we can try to get a solution working. 

My time will be a little more limited through at least through the end of the year so I'm laying out my plans for the next little bit. Most likely, no new controls or features will be going into v2.0 at this point. It will just be bug fixes and ensuring compatibility with remaining changes for 11.0 upstream.

[Still todo before v2 release]
- [ ] Add simple docs site (via github pages) for basic documentation for FA
  - I've realized my only documentation is really in the sample app, which isn't ideal since you have to download and run it to see everything. So as part of my Sample App refactor, I'm going add a small documentation thing for things like getting started, basic info about controls, etc. Examples will still be in the sample app. Most of this will be auto-generated for my sake. 
- [ ] Sample app clean up/face lift (also move sample app and FASandbox project into /samples directory for organization)
- [ ] Code clean up (try to reduce warnings)
- [ ] [Will add more if/as things come up]

**PLEASE NOTE**
- Until more documentation is available, please read the AppWindow PR for how to use AppWindow, including the necessary steps for styling and TaskDialog to work. 
- Please do not submit any PRs for changes in the sample app, until changes are done

<br />
<br/>
To recap what's been done so far (major features and PRs):

[Preview1]
- All controls were updated to use ControlThemes
- Controls/classes with duplicated names from upstream were given a 'FA' prefix
- See (#188) for full details

[Preview2]
- Minimal Localization was introduced for some FA controls ported from WinUI
- TeachingTip was ported
- PRs
  - #191
  - #195
  - #197
  - #199
  - #202
  - #203
  - #205

[Preview3]
- CoreWindow deprecated and replaced by AppWindow
- Move AppWindow to new package FluentAvalonia.UI.Windowing
- Added SettingsExpander control
- Improved navigation in Frame to allow resolving view by type or view model
- Improved system theme and accent color detection in linux
- Added TextVerticalAlignmentOverrideBehavior to FATheme for text positioning in some controls when Segoe fonts aren't available
- PRs
  - #210
  - #211 
  - #217 
  - #219 
  - #222 
  - #223 
  - #224 
  - #227 

[Preview4]
- Update compatibility for 11.0-preview4
- Updates to TabView
- PRs
  - #229
  - #230 
  - #241

[Preview5]
Lot's of changes here, too many to list, so please see these PRs. Note preview5 contains many breaking changes
Most notable changes:
- ThemeDictionary support & improved theme switching
- Standardized to IconSource over FAIconElement
- Some DirectProperties were moved to StyledProperty
- For everything else, see these PRs
- #253
- #271
- #283 
- #284
- #285 

As a reminder, the HighContrast theme is broken in preview5 pending a fix for DynamicResource upstream.

**Comment by stevemonaco** [comment]
Avalonia 11-preview4 has made breaking changes to `TextLayout`'s [constructors](https://github.com/AvaloniaUI/Avalonia/blob/c1fbc179c7b2c2f320a14a5846fce9e4e8d70bbc/src/Avalonia.Base/Media/TextFormatting/TextLayout.cs#L37) to add `letterSpacing`. I got this exception in 2.0.0-preview3:

```
System.MissingMethodException: Method not found: 'Void Avalonia.Media.TextFormatting.TextLayout..ctor(System.String, Avalonia.Media.Typeface, Double, Avalonia.Media.IBrush, Avalonia.Media.TextAlignment, Avalonia.Media.TextWrapping, Avalonia.Media.TextTrimming, Avalonia.Media.TextDecorationCollection, Avalonia.Media.FlowDirection, Double, Double, Double, Int32, System.Collections.Generic.IReadOnlyList`1<Avalonia.Utilities.ValueSpan`1<Avalonia.Media.TextFormatting.TextRunProperties>>)'.
   at FluentAvalonia.UI.Controls.FontIcon.GenerateText()
```

Besides that, `SelectableTextBlock` has been introduced and will probably need styling. I plan to try using it in `ContentDialog` for message boxes so the user can select and copy the body text.

**Comment by amwx** [comment]
FluentAvalonia v2-preview4 packages have been pushed

**Comment by Dynesshely** [comment]
Suggest VuePress as Docs site framework.

**Comment by AlphaNecron** [comment]
Make dynamic navigation icon as well as add Microsoft Store-like navigation view theme as a ControlTheme?
